"""empty message

Revision ID: 18ce1ba6ebed
Revises: 
Create Date: 2024-07-05 10:27:00.820805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ce1ba6ebed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_data',
    sa.Column('sn', sa.TEXT(), nullable=True),
    sa.Column('object type', sa.TEXT(), nullable=True),
    sa.Column('object', sa.TEXT(), nullable=True),
    sa.Column('time', sa.DATE(), nullable=True),
    sa.Column('Capacity usage(%)', sa.NUMERIC(), nullable=True),
    sa.Column('Mapped LUN capacity(MB)', sa.NUMERIC(), nullable=True),
    sa.Column('Total capacity(MB)', sa.NUMERIC(), nullable=True),
    sa.Column('Used capacity(MB)', sa.NUMERIC(), nullable=True),
    sa.Column('array_num', sa.TEXT(), nullable=True)
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('real_data')
    # ### end Alembic commands ###
