"""
Константы api_manager.
"""

import os


API_SECRET_KEY = os.environ.get('API_SECRET_KEY', 'dev')
API_URL_PREFIX = os.environ.get('API_URL_PREFIX', '/api')

LIFETIME_LAG = 30
ACCESS_TOKEN_LIFETIME_SECONDS = 3600
ACCESS_TOKEN_COOKIE_LIFETIME_SECONDS = (
    ACCESS_TOKEN_LIFETIME_SECONDS - LIFETIME_LAG
)

REFRESH_TOKEN_LIFETIME_SECONDS = 360000
REFRESH_TOKEN_COOKIE_LIFETIME_SECONDS = (
    REFRESH_TOKEN_LIFETIME_SECONDS - LIFETIME_LAG
)

TOKEN_TYPE = os.environ.get('TOKEN_TYPE', 'bearer')
